/*
 * generated by Xtext 2.11.0
 */
package com.rainerschuster.asdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AsdlStandaloneSetup extends AsdlStandaloneSetupGenerated {

	def static void doSetup() {
		new AsdlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
